development: &base
  adapter:  postgresql
  database: softcell_development
  encoding: utf8
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  host: localhost
  min_messages: error
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>

test: &test
  <<: *base
  database: softcell_test
